### PR TITLE
Adding a new option rocketInitialPoint where a user can customise sta…

### PR DESCRIPTION
**Pull request by adityasatnur**
Adding a new option rocketInitialPoint where a user can customise/set starting(initial) point of firework

### CODE REVIEW

**Review by filiptronicek — APPROVED** [review]

**Comment by adityasatnur** [comment]
Hey @tswaters is there any problem in merging my PR

**Comment by tswaters** [comment]
RIGHT, sorry I did see this right when you added it but haven't gotten around to looking into it yet.

The code looks fine.  I was thinking for creating a new feature, "cannons" that would allow for more configuration on the start position.....  basically an array of points.  Your option here would provide values to this new feature.... kust haven't gotten around to it yet.  

Let me get this merged/published anyway -- I'll look to get to this probably later today.  Assuming of course I can still remember how to build/deploy this project :)

**Comment by adityasatnur** [comment]
Sure. Thanks for the update!

**Comment by tswaters** [comment]
Thanks, I've cherry-picked this commit in and added you to contributes in package.json

This is now available in v2.5.1

**Pull request closed without merging**
